# Generated by Django 2.2 on 2021-05-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nominal',
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'валюта', 'verbose_name_plural': 'валюты'},
        ),
    ]
