# Generated by Django 2.2 on 2021-05-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210503_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название серии')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'серия',
                'verbose_name_plural': 'серии',
            },
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название валюты'),
        ),
    ]
