# Generated by Django 2.2 on 2021-05-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210503_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='description',
        ),
    ]
