# Generated by Django 2.2 on 2021-05-03 13:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_series_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Остаток')),
                ('weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес')),
                ('size', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Размер')),
                ('form', models.CharField(max_length=100, verbose_name='Форма')),
                ('year_of_issue', models.DateField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('year_of_issue_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания выпуска')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coins', to='webapp.Country', verbose_name='страна')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coins', to='webapp.Currency', verbose_name='валюта')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coins', to='webapp.Material', verbose_name='материал')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coins', to='webapp.Series', verbose_name='серия')),
            ],
        ),
    ]
