# Generated by Django 2.2 on 2021-05-03 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_coin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={'verbose_name': 'монета', 'verbose_name_plural': 'монеты'},
        ),
        migrations.AlterField(
            model_name='coin',
            name='nominal',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='номинал'),
        ),
    ]
