# Generated by Django 2.2 on 2021-05-04 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20210503_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='size',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес'),
        ),
    ]
