# Generated by Django 2.2 on 2021-05-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20210504_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='size',
            field=models.CharField(max_length=100, verbose_name='размер'),
        ),
    ]
