# Generated by Django 2.2 on 2021-05-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20210504_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='coin_pics', verbose_name='картинка монеты'),
        ),
    ]
