# Generated by Django 2.2 on 2021-05-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_coin_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='year_of_issue',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='year_of_issue_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дата выпуска'),
        ),
    ]
