# Generated by Django 2.2 on 2021-05-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20210506_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='year_of_issue_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дата окончания выпуска'),
        ),
    ]
