# Generated by Django 2.2 on 2021-05-08 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0011_auto_20210506_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='coins', to=settings.AUTH_USER_MODEL, verbose_name='Коллекционер'),
        ),
    ]
