# Generated by Django 2.2 on 2021-05-31 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_coin_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='currencies', to='webapp.Country', verbose_name='страна'),
        ),
    ]
