# Generated by Django 2.2 on 2021-06-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20210531_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='series',
        ),
    ]
