# Generated by Django 2.2 on 2021-06-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_remove_coin_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='series',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Серии'),
        ),
    ]
