# Generated by Django 2.2 on 2021-06-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_coin_series'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Series',
        ),
    ]
