# Generated by Django 2.2 on 2021-06-15 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_auto_20210615_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin_in_collection',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
