# Generated by Django 2.2 on 2021-06-15 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_auto_20210615_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('years', models.CharField(blank=True, max_length=50, null=True, verbose_name='Года')),
                ('countries', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страны')),
                ('comment', models.TextField(blank=True, max_length=400, null=True, verbose_name='Комментарий')),
                ('coins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='webapp.Material', verbose_name='монеты')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
    ]
