# Generated by Django 2.2 on 2021-06-17 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_collection_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='coins',
        ),
    ]
