# Generated by Django 2.2 on 2021-06-17 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_remove_collection_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin_in_collection',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coins_coll', to='webapp.Collection', verbose_name='коллекция'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='coins', to=settings.AUTH_USER_MODEL, verbose_name='создатель'),
        ),
    ]
