# Generated by Django 2.2 on 2021-06-17 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_auto_20210617_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin_in_collection',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins_coll', to='webapp.Collection', verbose_name='коллекция'),
        ),
    ]
