# Generated by Django 2.2 on 2021-06-20 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_auto_20210617_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin_in_collection',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
