# Generated by Django 2.2 on 2021-06-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_auto_20210621_1359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coin_in_Collection',
        ),
    ]
