# Generated by Django 2.2 on 2021-06-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_delete_coin_in_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='owner',
        ),
    ]
