# Generated by Django 2.2 on 2021-06-21 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_remove_coin_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coin', to='webapp.Country', verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coin', to='webapp.Currency', verbose_name='валюта'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coin', to='webapp.Material', verbose_name='материал'),
        ),
    ]
