# Generated by Django 2.2 on 2021-06-23 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_coin_in_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin_in_collection',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coins', to=settings.AUTH_USER_MODEL, verbose_name='создатель'),
        ),
    ]
