# Generated by Django 2.2 on 2021-06-24 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0038_auto_20210623_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='webapp.Coin_in_Collection', verbose_name='монета')),
                ('to_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_exchanges', to='webapp.Coin_in_Collection', verbose_name='на монету')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'предложение',
                'verbose_name_plural': 'предложения',
            },
        ),
    ]
