# Generated by Django 2.2 on 2021-06-24 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0039_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='webapp.Coin_in_Collection', verbose_name='монета'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='to_coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_offers', to='webapp.Coin_in_Collection', verbose_name='на монету'),
        ),
    ]
